const mongoose = require('mongoose');

const urlSchema = new mongoose.Schema({

    // shortId will be generated by the server
    // redirectUrl will be provided by the user

    shortId: {
        type: String,
        required: true,
        unique: true
    },
    redirectUrl: {
        type: String,
        required: true
    },
    visitTime: [{ timestamp: { type: String } }],

},
    { timestamps: true }
);
const URL= mongoose.model('URL', urlSchema);
module.exports = URL;